# ===================================================
# meta infos
# ===================================================

meta:
  project: ci.os.lmp
  include:
    - mender-on-verdin-tdx-dunfell/dobi.yaml

# ===================================================
# alias
# ===================================================

alias=mvtd-yocto-shell:
  tasks:
    - mender-on-verdin-tdx-dunfell-yocto-shell
  annotations:
    description: "[alias] mender-on-verdin-tdx-dunfell-yocot-shell"

alias=mvtd-build-min:
  tasks:
    - mender-on-verdin-tdx-dunfell-build-minimal-image
  annotations:
    description: "[alias] mender-on-verdin-tdx-dunfell-build-minimal-image"

alias=build-all:
  tasks:
    - mender-on-verdin-tdx-dunfell-build-minimal-image
  annotations:
    description: "[alias] build all images"

