# ===================================================
# meta infos
# ===================================================

meta:
  project: ci.os.lmp
  include:
    - version.yaml
    - dobi.yaml
    - tools/curl/dobi.yaml
    - mender-on-verdin/dobi.yaml

# ===================================================
# alias
# ===================================================

alias=version:
  tasks:
    - buildingblock-version

alias=build-all:
  tasks:
    - mender-on-verdin-build-minimal-image
  annotations:
    description: "[alias] build all images"

