# ===================================================
# meta infos
# ===================================================

meta:
  project: ci.os.lmp
  include:
    - version.yaml
    - mender-on-verdin-tdx-dunfell/dobi.yaml

# ===================================================
# alias
# ===================================================

alias=version:
  tasks:
    - buildingblock-version

alias=mvtd-yocto-shell:
  tasks:
    - buildingblock-version

alias=build-all:
  tasks:
    - mender-on-verdin-build-minimal-image
  annotations:
    description: "[alias] build all images"

