# ===================================================
# meta infos
# ===================================================

meta:
  project: ci.os.lmp
  include:
    - version.yaml
    - dobi.yaml
    - yocto/.generated_cpu01-bringup.yaml
    - yocto/.generated_cpu01-edgefarm.yaml
    - yocto/.generated_verdindev-edgefarm.yaml

# ===================================================
# alias
# ===================================================

alias=version:
  tasks:
    - buildingblock-version

alias=build-all:
  tasks:
    - cpu01-bringup-build-image
    - cpu01-edgefarm-build-image
    - verdindev-edgefarm-build-image
  annotations:
    description: "\t\t\t--> [alias]build all images"

