# ===================================================
# meta infos
# ===================================================

meta:
  project: ci.os.lmp
  include:
    - version.yaml
    - dobi.yaml
    - tools/curl/dobi.yaml
    - moducop-cpu01/dobi.yaml
    - verdindevboard/dobi.yaml

# ===================================================
# alias
# ===================================================

alias=version:
  tasks:
    - buildingblock-version

alias=build-all:
  tasks:
    - verdindevboard-build-bringup-image
    - moducop-cpu01-build-bringup-image
  annotations:
    description: "[alias] build all images"

