resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: pull-request
    type: pull-request
    check_every: 30s
    webhook_token: ((webhook_token))
    source:
      repository: ci4rail/ci.os.lmp
      access_token: ((access_token))

  # Git sources
  - name: source
    type: git
    source:
      uri: ((git_source))
      private_key: ((privatekey))
      branch: ((git_branch))
      paths: ((git_paths))
      skip_ssl_verification: ((git_skip_ssl_verification))

jobs:
  - name: build
    public: true
    plan:
      - get: pull-request
        trigger: true
        version: every
        on_failure:
          put: pull-request
          params:
            path: pull-request
            status: failure
      - get: source

      - task: generate-version
        file: source/yocto/ci/task_cfg_generate_version.yaml

      - task: build-tezi-file
        file: source/yocto/ci/task_cfg_build_tezi_file.yaml
        vars:
          name: ((name))
          MENDER_ARTIFACT_DEV_SUFFIX: ((MENDER_ARTIFACT_DEV_SUFFIX))
          MENDER_SERVER_URL: ((MENDER_SERVER_URL))
          MENDER_TENANT_TOKEN: ((MENDER_TENANT_TOKEN))
          IMAGE_NAME_SUFFIX: ((IMAGE_NAME_SUFFIX))

      - put: pull-request
        params:
          path: pull-request
          status: pending

      - put: pull-request
        params:
          path: pull-request
          status: success
