platform: linux

image_resource:
  type: registry-image
  source:
    repository: cfmanteiga/alpine-bash-curl-jq
    tag: latest

inputs:
  - name: s3-gitversion
outputs:
  - name: build-envs
run:
  path: /bin/bash
  args:
    - -c
    - |
      echo Generating build environment variables:
      echo MENDER_ARTIFACT_DEV_SUFFIX=((MENDER_ARTIFACT_DEV_SUFFIX)) > build-envs/env
      echo IMAGE_NAME_SUFFIX=((IMAGE_NAME_SUFFIX)) >> build-envs/env
      echo MENDER_ARTIFACT_NAME=((name))-$(cat s3-gitversion/gitversion/plain/BranchVersion)${MENDER_ARTIFACT_DEV_SUFFIX} >> build-envs/env
      echo MENDER_SERVER_URL=((MENDER_SERVER_URL)) >> build-envs/env
      echo MENDER_TENANT_TOKEN=((MENDER_TENANT_TOKEN)) >> build-envs/env
      echo HOSTED_MENDER_USER_EMAIL=((HOSTED_MENDER_USER_EMAIL)) >> build-envs/env
      echo HOSTED_MENDER_PASSWORD=((HOSTED_MENDER_PASSWORD)) >> build-envs/env
      echo IMAGE_GIT_VERSION=$(cat s3-gitversion/gitversion/plain/BranchVersion) >> build-envs/env
